name = "cynthia_websites_mini_shared"
target = "javascript"
[javascript]
runtime = "bun"
typescript_declarations = true

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
plinth = ">= 0.5.6 and < 1.0.0"
gleam_json = ">= 2.3.0 and < 3.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
bungibindies = "1.1.5"
