name: autofix.ci
on:
  pull_request:
  push:
permissions: {}
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: |
          bun x prettier . --write 
          git restore --source=HEAD --staged --worktree -- ./.github
      - uses: autofix-ci/action@v1
        with:
          commit-message: "Apply Prettier format"
  buildscript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: |
          mise run fmt-all
      - uses: autofix-ci/action@v1
        with:
          commit-message: "Apply build script's format"
