name: Release cynthiaweb-mini

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write

jobs:
  build:
    name: Build ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - os: ubuntu
            runner: ubuntu-latest
            arch: x64
            ext: ""
            bin_name: cynthiaweb-mini-linux-x64
          - os: windows
            runner: windows-latest
            arch: x64
            ext: ".exe"
            bin_name: cynthiaweb-mini-windows-x64.exe
          - os: macos
            runner: macos-latest
            arch: arm64
            ext: ""
            bin_name: cynthiaweb-mini-macos-intel
          - os: macos
            runner: macos-13
            arch: intel
            ext: ""
            bin_name: cynthiaweb-mini-macos-x64
          - os: ubuntu
            runner: ubuntu-24.04-arm
            arch: arm64
            ext: ""
            bin_name: cynthiaweb-mini-linux-arm64
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: gleam-lang/setup-gleam@v1.0.2
        if: runner.os != 'Windows'
        with:
          gleam-version: "1.9.1"
      - name: Install Gleam on Windows
        if: runner.os == 'Windows'
        run: |
          winget install gleam.gleam -s winget
      - name: Build and bundle
        run: |
          bun install
          bun bundle
          bun build --compile dist/cynthia_websites_mini_server.js --outfile ./${{ matrix.bin_name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.bin_name }}
          path: ./${{ matrix.bin_name }}

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        run: |
          for file in ./artifacts/**/cynthiaweb-mini*; do
            gh release upload "${{ github.ref_name }}" "$file"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
