name: Client tests

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: gleam-lang/setup-gleam@v1.0.2
        with:
          gleam-version: "1.8.1"
      - run: bun install
      - run: bun ./build.ts client-gleam deps download
      - run: bun ./build.ts test client
